repos :
- repo : local
  hooks :
  - id : MyTests
    name : Run my tests
    entry : python 
    language : system
    args: [pre_commit_tests.py]

  - id : MyTests2
    name : Run my tests2
    entry : python 
    language : system
    stages: [push]
    args: [pre_push_tests.py]

  - id : MyTests3
    name : Run my tests3
    entry : python 
    language : system
    stages: [commit-msg]
    args: [commit_msg_tests.py]

  - id : MyTests4
    name : Run my tests4
    entry : python 
    language : system
    stages: [post-commit]
    args: [post_commit_tests.py]